In [6]:
'''
http://www.practicepython.org/exercise/2017/02/06/34-birthday-json.html
>>> Welcome to the birthday dictionary. We know the birthdays of:
Albert Einstein
Benjamin Franklin
Ada Lovelace
>>> Who's birthday do you want to look up?
Benjamin Franklin
>>> Benjamin Franklin's birthday is 01/17/1706.
Make the data into JSON instead

'''
import pandas as pd
import json
import numpy as np
from pprint import pprint


#arr = np.array([])
name_list = []
birthday_list = []
add_recrod = {}
with open("birthdayJSON.json", "r") as f:
    birthdayDB = json.load(f)
    pprint(birthdayDB)
    #print(birthdayDB['Birthdays'][0]['name'])
    print(type(birthdayDB['Birthdays'][0]['name']))

    df = pd.DataFrame(birthdayDB)            #using panda DataFrame here. 
    print(df)
    #print(df["Birthdays"][0][['name','birthday']])
    #print(df["Birthdays"])
    print(df["Birthdays"][0]['name'])
    print(df["Birthdays"][0]['birthday'])
    
    #print(df["Birthdays"][1]['name'])
    loop = len(df["Birthdays"])
    print("List of people you can choose from: ")
    for i in range(0,loop):
        #print(df["Birthdays"][i]['name'])
        name_data = df["Birthdays"][i]['name']  ##this works
        birthday_data = df["Birthdays"][i]['birthday']
        #np.insert(arr,name_data)
        name_list.append(name_data)
        birthday_list.append(birthday_data)
        
        
    print(name_list)
    print(birthday_list)
    print(type(name_list))
    name_array = np.asarray(name_list)
    birthday_array = np.asarray(birthday_list)
    print(name_array)
    print(type(name_array))
    index_df = pd.DataFrame({'index':[1,2,3,4,5]})
    
    name_df = pd.DataFrame({'names':name_array})
    birthday_df = pd.DataFrame({'birthday':birthday_array})
    print(index_df)
    print(name_df)
    print(birthday_df)
    testing_df = pd.concat([name_df, birthday_df], sort=False, axis=1)
    print(testing_df)
    print(testing_df.index)
    print(f'This is the shape of the dataframe: {testing_df.shape}')
    print(testing_df.loc[0, "birthday"])
    #print(testing_df[0])
    #name_df = pd.append(index_df)
    #we are going to use pd.concat()function to join the dataframes
    #There are 3 Dataframes here: 1. index_df, 2. name_df 
    #index is for Identification, alignment and selection
    #pd.DataFrame(index = ['pbp'], columns = ['a','b'], dtype = np.dtype([('str','float')])) 
    df_empty = pd.DataFrame(['name', 'birthday'])
    
    
    #import numpy as np
    #myarray = np.asarray(mylist)
        
    #  numpy.insert(arr, obj, values, axis=None)[source]
########################################################################################
print("Welcome to the birthday dictionary. We know the birthdays of:")
print(name_df)
input_num = int(input("Please input an index next to the name to find out the birthday: "))
print(type(input_num))
selected = testing_df.loc[input_num, 'names']
ans_record = testing_df.loc[input_num, 'birthday']
print(f'You have selected: {selected}')
print(f'The birtyday is: {ans_record}')

while True:
    additional_name = str(input("Please input a name of a famous person to add: "))
    print(f'You have inputted: {additional_name}')
    additional_birthday = input("Please input birthday of the person above: ")
    print(f'You have inputted: {additional_birthday}')

    print(type(additional_birthday))
    #Store this as series or pd.series() instead...
    #add_series = pd.Series({'name':[additional_name], 'birthday':[additional_birthday]})
    add_series = pd.Series([additional_name, additional_birthday], index=['names','birthday'])

    print(add_series)    #additional_record
    pprint(add_series)
    testing_df = testing_df.append(add_series, ignore_index = True)    ##here is the changed line
    pprint(testing_df)
    
    more_data = input("Do you want to add more? (type: Y/N): ")
    more_data = more_data.lower()
    print(more_data)
    if more_data == 'y':
        continue
    else: 
        break
testing_df.to_json('modified_names.json')
        
#pd.concat([testing_df, add_series], axis =0)


'''
https://eulertech.wordpress.com/2017/11/28/pandas-valueerror-if-using-all-scalar-values-you-must-pass-an-index/
Then, to save your dictionary to disk you need to open a file and use the json.dump() method.
Remember to use the w flag when opening a file for writing:

with open("info.json", "w") as f:
    json.dump(info_about_me, f)
'''


{'Birthdays': [{'birthday': 'Jan 1st, 1900', 'name': 'DItoga'},
               {'birthday': 'March 14, 1879', 'name': 'Albert Einstein'},
               {'birthday': 'January 17, 1706', 'name': 'Benjamin Franklin'},
               {'birthday': 'February 12, 1809', 'name': 'Abraham Lincoln'},
               {'birthday': 'June 12th, 1924', 'name': 'George HW Scherff'}]}
<class 'str'>
                                           Birthdays
0    {'name': 'DItoga', 'birthday': 'Jan 1st, 1900'}
1  {'name': 'Albert Einstein', 'birthday': 'March...
2  {'name': 'Benjamin Franklin', 'birthday': 'Jan...
3  {'name': 'Abraham Lincoln', 'birthday': 'Febru...
4  {'name': 'George HW Scherff', 'birthday': 'Jun...
DItoga
Jan 1st, 1900
List of people you can choose from: 
['DItoga', 'Albert Einstein', 'Benjamin Franklin', 'Abraham Lincoln', 'George HW Scherff']
['Jan 1st, 1900', 'March 14, 1879', 'January 17, 1706', 'February 12, 1809', 'June 12th, 1924']
<class 'list'>
['DItoga' 'Albert Einstein' 'Benjamin

'\nhttps://eulertech.wordpress.com/2017/11/28/pandas-valueerror-if-using-all-scalar-values-you-must-pass-an-index/\nThen, to save your dictionary to disk you need to open a file and use the json.dump() method.\nRemember to use the w flag when opening a file for writing:\n\nwith open("info.json", "w") as f:\n    json.dump(info_about_me, f)\n'

In [33]:
!pip install pandas
!pip install numpy

In [9]:
a = np.array(np.arange(24)).reshape(2,3,4)
a


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [10]:
c = np.array(np.arange(36).reshape(6,6))

In [11]:
c


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [12]:
b = np.append(c, [0,1,2,3,4,5])

In [13]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35,  0,  1,  2,  3,  4,  5])

In [14]:
x = np.empty(5)
x    #this is dynamic....not 0 because it is not initialized

array([0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 7.50979782e-321,
       3.97476069e-304])

In [16]:
y = np.empty([2,3])
y

array([[2.16332808e-304, 9.15951656e-304, 2.85809440e-288],
       [2.86361669e-302, 1.99025274e-290, 4.70531138e-271]])

In [7]:
import pandas as pd
import numpy as np
import json
from pprint import pprint 
with open("birthdayJSON.json", "r") as f:
    birthdayDB = json.load(f)
    #print(birthdayDB)
    pprint(birthdayDB)
    
    
    

{'Birthdays': [{'birthday': 'Jan 1st, 1900', 'name': 'DItoga'},
               {'birthday': 'March 14, 1879', 'name': 'Albert Einstein'},
               {'birthday': 'January 17, 1706', 'name': 'Benjamin Franklin'},
               {'birthday': 'February 12, 1809', 'name': 'Abraham Lincoln'},
               {'birthday': 'June 12th, 1924', 'name': 'George HW Scherff'}]}


In [4]:
import pandas as pd
from pprint import pprint

my_series = pd.Series({'London':10, 'Tripoli':100, 'Cairo':10})
pprint(my_series)

London      10
Tripoli    100
Cairo       10
dtype: int64


In [ ]:
#  Pandas support various IO types so it is going to be easy
#https://www.youtube.com/watch?v=9Z7wvippeko&index=3&list=PLQVvvaa0QuDc-3szzjeP6N6b0aDrrKyL-
#www.quandl.com    for data
#http://pandas.pydata.org/pandas-docs/stable/io.html
