In [11]:
import numpy as np
a = np.array([4,5,6,8,11,15])
print(a)
a[0]
b = np.arange(3,50,3)
print(b)

c = np.linspace(0,120, 25)    #creates floating space array!   evenly spaced w 25....elements
print(c)
print(len(c))         #There are 25 elements as suggested above
c.reshape(5,5)        #reshape creates 2 dimeisional array!!

[ 4  5  6  8 11 15]
[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48]
[  0.   5.  10.  15.  20.  25.  30.  35.  40.  45.  50.  55.  60.  65.
  70.  75.  80.  85.  90.  95. 100. 105. 110. 115. 120.]
25


array([[  0.,   5.,  10.,  15.,  20.],
       [ 25.,  30.,  35.,  40.,  45.],
       [ 50.,  55.,  60.,  65.,  70.],
       [ 75.,  80.,  85.,  90.,  95.],
       [100., 105., 110., 115., 120.]])

In [2]:
import numpy as np
b = np.arange(3,50,3)
print(b)

[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48]


In [7]:
import numpy as geek 
  
#Working on 1D 
arr = geek.arange(5) 
print("arr : \n", arr) 
print("Shape : ", arr.shape) 
object = 2
a = geek.delete(arr, object) 
print("\ndeleteing arr 2 times : \n", a) 
print("Shape : ", a.shape) 
  

arr : 
 [0 1 2 3 4]
Shape :  (5,)

deleteing arr 2 times : 
 [0 1 3 4]
Shape :  (4,)


In [9]:
import numpy as geek 
arr = geek.arange(5) 
print("1D arr : \n", arr) 
print("Shape : ", arr.shape) 

# value = 9 
# index = 1    
# Insertion before first index 
a = geek.insert(arr, 1, 9)   #syntax insert(array_name, index, value)
print("\nArray after insertion : ", a) 
print("Shape : ", a.shape) 
  

1D arr : 
 [0 1 2 3 4]
Shape :  (5,)

Array after insertion :  [0 9 1 2 3 4]
Shape :  (6,)


In [12]:
c = c.reshape(5,5)
c.size     #size is an attribute not a function  =>  not callable...
print(c.size)
c.shape    #Shape gives you what type of matrix this is  also attribute so not callable.
c.dtype    #dtype gives you data type. c for example is dtype('float64')
c.itemsize  #this gives 8

d = np.array([(4,5,6,7),(3,2,7,10)])    #two dimemsional array creation using np.array and syntax
print(d)
print(d[0])
d<4                        ##This is sooo COOL!! 
e = np.ones((4,5))
print(e)                ## Sooo cool, in creating matrix that is like for booleanQ

25
[[ 4  5  6  7]
 [ 3  2  7 10]]
[4 5 6 7]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [24]:
g =np.random.random((2,3))   #creates 2x3 random arran for you...but not int here...this is from 0 to 1 as in probability
print(g)

[[0.90084042 0.57007267 0.34937006]
 [0.57560989 0.67755363 0.16298855]]


In [26]:
h = np.random.randint(0,100,5)
print(h)

[73  3  3 69 23]


In [27]:
print(h.sum())

171


In [33]:
print(h.min())
print(h.max())
print(h.mean())
print(h.var())   ##variance 
print(h.std())   ##Standard Deviation

3
73
34.2
957.76
30.94769781421552


In [ ]:
datafile = np.loadtext()  ##16:18  https://www.youtube.com/watch?v=8Mpc9ukltVA    //genfromtxt handles errors and missing data better. 

In [19]:
import numpy as np
letter = np.array(['_']*5)
print(letter)
print(letter[1])


['_' '_' '_' '_' '_']
_
